Repository dhruvdev01/HomeDog, pull requests merged in 2022-10, with the labels that each got.

#1 Create index.js
  store/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#2 yarn-update
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#4 Readme_change
  README.md
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#3 node-dependencies
  README.md
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest-accepted
